### ISSUE TITLE
Does not work with livestreams

### ISSUE THREAD

**Issue by findirfin** [AbeNaws/Mloader#3]
I tried to download this live stream, and it didn't work. Here is the message.BTW I'm doing this on Kali Linux because that's what I heard the project was developed on. 

`┌──(kali㉿kali)-[~/Downloads/Mloader-main]
└─$ python3 Mloader.py
Url: https://www.youtube.com/watch?v=jfKfPfyJRdk
----------------------------------------------------
Song: lofi hip hop radio 📚 - beats to relax/study to
----------------------------------------------------
Downloading: lofi hip hop radio 📚 - beats to relax/study to
Traceback (most recent call last):
  File "/home/kali/Downloads/Mloader-main/Mloader.py", line 111, in <module>
    process_video(yt, downloaded_songs_folder, converted_songs_folder)
  File "/home/kali/Downloads/Mloader-main/Mloader.py", line 52, in process_video
    audio_stream = video.streams.filter(only_audio=True).first()
                   ^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/__main__.py", line 233, in check_availability
    raise exceptions.LiveStreamError(video_id=self.video_id)
pytube.exceptions.LiveStreamError: jfKfPfyJRdk is streaming live and cannot be loaded
`

**Comment by AbeNaws** [comment]
This project is not meant to download live streams.
